services:
  summary-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summary-generator
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TELEGRAM_SESSION_PHONE_NUMBER: ${TELEGRAM_SESSION_PHONE_NUMBER}
      BOT_TOKEN: ${BOT_TOKEN}
      SESSIONS_PATH: ${SESSIONS_PATH}
      TELETHON_SESSION_NAME: ${TELETHON_SESSION_NAME}
      BOT_SESSION_NAME: ${BOT_SESSION_NAME}
      DEFAULT_SUMMARY_LENGTH: ${DEFAULT_SUMMARY_LENGTH}
    volumes:
      - ./sessions:/app/sessions
    command: python main.py
